### ISSUE TITLE
Confusing wording about data storage in /home

### ISSUE THREAD

**Issue by jennydaman** [northeastern-rc/rc-public-documentation#319]
https://github.com/northeastern-rc/rc-public-documentation/blob/5bbf6265171891105c8d735d3a7fab33ea6c139e/docs/source/datamanagement/discovery_storage.md?plain=1#L16

> While `/home` **is permanent storage** backed up and replicated, `/home` **is not permanent storage.**

Could this be clarified?

**Comment by SerenaCaplins** [comment]
Thank you for this comment. We have clarified the language for /home which you can now see here: https://rc-docs.northeastern.edu/en/latest/datamanagement/discovery_storage.html
