### ISSUE TITLE
Bug: Missing hardware-overview

### ISSUE THREAD

**Issue by maxedhunter** [northeastern-rc/rc-public-documentation#336]
I was searching for the table of GPUs and how many are public/private/on the cluster and found it was no longer in the same location. In the commit history I see it moved to hardware-overview which seems to be a dead link in several pages (faq and transfer data).

**Comment by SerenaCaplins** [comment]
This information is now on the website https://rc.northeastern.edu/compute/
https://rc.northeastern.edu/partitions/
